import {describe,expect,it} from "vitest";
import {demoVehicles} from "@/lib/demo-data";
import {rankVehicles,scoreCarForPreferences} from "./engine";
import {defaultPreference} from "./criteria";
import type {CarPreference,Vehicle} from "@/types";
const p=(over:Partial<CarPreference>={}):CarPreference=>({...defaultPreference,budget:{max:5_000_000},priorities:{...defaultPreference.priorities,reliability:1,fuelEconomy:1},...over});
describe("soft DSS ranking",()=>{
 it("keeps over-budget, wrong-body and wrong-transmission cars",()=>{const result=rankVehicles(demoVehicles,p({preferredBodyTypes:["SUV"],transmission:"MANUAL"}));expect(result.ranked).toHaveLength(demoVehicles.length);expect(result.ranked.some(x=>x.vehicle.price>5_000_000)).toBe(true);expect(result.ranked.some(x=>x.vehicle.bodyType!=="SUV")).toBe(true);expect(result.ranked.some(x=>x.vehicle.transmission!=="MANUAL")).toBe(true)});
 it("can rank a slightly over-budget strong match above a weak cheaper car",()=>{const strong={...demoVehicles[4],price:5_250_000,reliabilityRating:98,fuelEconomyRating:95},weak={...demoVehicles[0],id:"weak",price:4_500_000,reliabilityRating:20,fuelEconomyRating:20};expect(rankVehicles([weak,strong],p({preferredBodyTypes:["SUV"],transmission:"AUTOMATIC"})).ranked[0].vehicle.id).toBe(strong.id)});
 it("uses a gradual budget penalty and explains it",()=>{const slight=scoreCarForPreferences({...demoVehicles[0],price:5_500_000},p()),far=scoreCarForPreferences({...demoVehicles[0],price:9_000_000},p());expect(slight.score).toBeGreaterThan(far.score);expect(slight.tradeOffs).toContain("\u20A6500k above your budget")});
 it("excludes skipped criteria from normalization",()=>{const result=scoreCarForPreferences(demoVehicles[0],{...defaultPreference,budget:{max:5_000_000}});expect(result.maximumScore).toBe(30);expect(result.breakdown).toHaveLength(1);expect(result.score).toBe(100)});
 it("treats missing data neutrally rather than as mismatch",()=>{const pref=p({budget:undefined,priorities:{...defaultPreference.priorities,reliability:1}}),missing=scoreCarForPreferences({...demoVehicles[0],reliabilityRating:undefined},pref),mismatch=scoreCarForPreferences({...demoVehicles[0],reliabilityRating:20},pref);expect(missing.breakdown[0].state).toBe("UNKNOWN");expect(mismatch.breakdown[0].state).toBe("MISMATCH");expect(missing.score).toBeGreaterThan(mismatch.score)});
 it("normalizes whole scores and sorts deterministically",()=>{const same=(id:string,year:number):Vehicle=>({...demoVehicles[0],id,year});const result=rankVehicles([same("b",2020),same("a",2020),same("c",2022)],{...defaultPreference,budget:{max:5_000_000}});expect(result.ranked.map(x=>x.vehicle.id)).toEqual(["c","a","b"]);expect(result.ranked.every(x=>Number.isInteger(x.score)&&x.score>=0&&x.score<=100)).toBe(true)});
 it("only returns empty for empty inventory and handles one or imperfect candidates",()=>{expect(rankVehicles([],p()).ranked).toEqual([]);expect(rankVehicles([demoVehicles[0]],p()).ranked).toHaveLength(1);expect(rankVehicles(demoVehicles,p({budget:{max:100_000},preferredBodyTypes:["CONVERTIBLE"],transmission:"MANUAL"})).ranked).toHaveLength(demoVehicles.length)});
});
