import {criteria} from "./criteria";
import {formatCompactNaira} from "./money";
import type {CarPreference,DecisionUseCase,PriorityKey,Vehicle} from "@/types";
export type CriterionState="MATCH"|"MISMATCH"|"UNKNOWN"|"PARTIAL";
export type ScoreBreakdownItem={key:string;label:string;weight:number;value:number;points:number;state:CriterionState;detail:string};
export type RecommendationScore={vehicle:Vehicle;score:number;rawScore:number;maximumScore:number;strongMatches:number;withinBudget:boolean;budgetDistance:number;breakdown:ScoreBreakdownItem[];reasons:string[];tradeOffs:string[];unknowns:string[]};
export const MATCH_WEIGHTS={budget:30,useCase:18,bodyType:16,priorities:26,transmission:10,fuelType:8,seats:8,year:8,origin:6,brand:6,engine:6,mileage:6} as const;
const ratingFor:Record<PriorityKey,(v:Vehicle)=>number|undefined>={fuelEconomy:v=>v.fuelEconomyRating,reliability:v=>v.reliabilityRating,maintenance:v=>v.maintenanceCostRating,comfort:v=>v.comfortRating,performance:v=>v.performanceRating,practicality:v=>v.practicalityRating,appearance:v=>v.condition.body};
const labelFor=Object.fromEntries(criteria.map(item=>[item.key,item.label])) as Record<PriorityKey,string>;
function average(values:(number|undefined)[]){const known=values.filter((value):value is number=>value!==undefined);return known.length?known.reduce((sum,value)=>sum+value,0)/known.length:undefined}
function mainUseValue(v:Vehicle,useCase:DecisionUseCase){switch(useCase){case "DAILY":return average([v.fuelEconomyRating,v.maintenanceCostRating,v.reliabilityRating]);case "FAMILY":return average([v.practicalityRating,v.comfortRating,v.numberOfSeats===undefined?undefined:v.numberOfSeats>=5?95:35]);case "BUSINESS":return average([v.maintenanceCostRating,v.reliabilityRating,v.fuelEconomyRating]);case "LONG_DISTANCE":return average([v.comfortRating,v.reliabilityRating,v.fuelEconomyRating]);case "ROUGH_ROADS":return average([v.condition.suspension,["SUV","PICKUP"].includes(v.bodyType)?92:55]);case "PERFORMANCE":return v.performanceRating;case "LUXURY":return average([v.comfortRating,v.condition.interior,v.condition.body]);}}
const state=(value:number):CriterionState=>value>=80?"MATCH":value<50?"MISMATCH":"PARTIAL";
function add(items:ScoreBreakdownItem[],key:string,label:string,weight:number,value:number|undefined,detail:string,unknown:string){const evaluated=value??55;items.push({key,label,weight,value:Number(evaluated.toFixed(1)),points:Number((evaluated*weight/100).toFixed(2)),state:value===undefined?"UNKNOWN":state(evaluated),detail:value===undefined?unknown:detail})}
function budgetFit(price:number,budget:number){if(price<=budget)return 100;const over=(price-budget)/budget;if(over<=.1)return 100-over*150;if(over<=.25)return 85-(over-.1)*200;if(over<=.5)return 55-(over-.25)*120;return Math.max(5,25-(over-.5)*25)}
export function scoreCarForPreferences(v:Vehicle,p:CarPreference):RecommendationScore{
 const b:ScoreBreakdownItem[]=[],budget=p.budget?.max;
 if(budget!==undefined){const over=Math.max(0,v.price-budget);add(b,"budget","Budget",MATCH_WEIGHTS.budget,budgetFit(v.price,budget),over?formatCompactNaira(over)+" above your budget":"Within your "+formatCompactNaira(budget)+" budget","Price is not supplied");if(over)b[b.length-1].state="PARTIAL"}
 if(p.useCase){const value=mainUseValue(v,p.useCase);add(b,"useCase","Main use",MATCH_WEIGHTS.useCase,value,value===undefined?"":Math.round(value)+"/100 fit for your main use","Not enough listing data to assess your main use")}
 if(p.preferredBodyTypes?.length){const match=p.preferredBodyTypes.includes(v.bodyType);add(b,"bodyType","Vehicle type",MATCH_WEIGHTS.bodyType,match?100:25,match?v.bodyType+" matches your preferred vehicle type":v.bodyType+" differs from your "+p.preferredBodyTypes.join(" or ")+" preference","")}
 const priorities=(Object.keys(p.priorities) as PriorityKey[]).filter(key=>p.priorities[key]>0);
 if(priorities.length){const total=priorities.reduce((sum,key)=>sum+p.priorities[key],0);for(const key of priorities){const rating=ratingFor[key](v);add(b,"priority:"+key,labelFor[key],MATCH_WEIGHTS.priorities*p.priorities[key]/total,rating,rating===undefined?"":labelFor[key]+" rating: "+rating+"/100",labelFor[key]+" has not been rated")}}
 if(p.preferredMakes?.length||p.excludedMakes?.length){const preferred=p.preferredMakes?.some(make=>make.toLowerCase()===v.make.toLowerCase()),excluded=p.excludedMakes?.some(make=>make.toLowerCase()===v.make.toLowerCase()),value=excluded?15:preferred?100:55;add(b,"brand","Manufacturer",MATCH_WEIGHTS.brand,value,excluded?v.make+" is a manufacturer you wanted to avoid":preferred?v.make+" matches your preferred manufacturer":v.make+" is outside your preferred manufacturers","")}
 if(p.transmission&&p.transmission!=="NO_PREFERENCE"){const match=v.transmission===p.transmission;add(b,"transmission","Transmission",MATCH_WEIGHTS.transmission,match?100:20,match?v.transmission.toLowerCase()+" transmission matches":v.transmission.toLowerCase()+" rather than "+p.transmission.toLowerCase(),"Transmission is not supplied")}
 if(p.fuelType&&p.fuelType!=="NO_PREFERENCE"){const match=v.fuelType===p.fuelType;add(b,"fuelType","Fuel type",MATCH_WEIGHTS.fuelType,match?100:30,match?v.fuelType.toLowerCase()+" matches your preference":v.fuelType.toLowerCase()+" differs from your "+p.fuelType.toLowerCase()+" preference","Fuel type is not supplied")}
 if(p.seatingCapacity?.minimum!==undefined){const seats=v.numberOfSeats,value=seats===undefined?undefined:seats>=p.seatingCapacity.minimum?100:Math.max(20,100-(p.seatingCapacity.minimum-seats)*30);add(b,"seats","Seats",MATCH_WEIGHTS.seats,value,seats!==undefined&&seats>=p.seatingCapacity.minimum?"Seats "+seats+", meeting your minimum":"Seats "+seats+", below your minimum of "+p.seatingCapacity.minimum,"Seat count is not supplied")}
 if(p.year?.min!==undefined){const difference=v.year-p.year.min;add(b,"year","Model year",MATCH_WEIGHTS.year,difference>=0?100:Math.max(20,100+15*difference),difference>=0?v.year+" meets your preferred minimum year":Math.abs(difference)+" year"+(difference===-1?"":"s")+" older than preferred","")}
 if(p.origin&&p.origin!=="NO_PREFERENCE"){const match=v.origin===p.origin;add(b,"origin","Condition",MATCH_WEIGHTS.origin,v.origin===undefined?undefined:match?100:30,match?"Matches your condition preference":(v.origin??"").replaceAll("_"," ").toLowerCase()+" differs from your preference","Vehicle condition category is not supplied")}
 if(p.engineHealth?.minimum!==undefined){const engine=v.condition.engine,value=engine===undefined?undefined:engine>=p.engineHealth.minimum?100:Math.max(15,100-(p.engineHealth.minimum-engine)*3);add(b,"engine","Engine condition",MATCH_WEIGHTS.engine,value,engine!==undefined&&engine>=p.engineHealth.minimum?"Engine rating meets your preference":"Engine rating is below your preference","Engine condition has not been rated")}
 if(p.mileage?.maximum!==undefined){const maximum=p.mileage.maximum,over=Math.max(0,v.mileage-maximum);add(b,"mileage","Mileage",MATCH_WEIGHTS.mileage,over===0?100:Math.max(15,100-over/maximum*100),over===0?"Within your preferred mileage":Math.round(over/1000)+"k km above your preferred mileage","")}
 const maximumScore=b.reduce((sum,item)=>sum+item.weight,0),rawScore=b.reduce((sum,item)=>sum+item.points,0),score=Math.round(Math.max(0,Math.min(100,maximumScore?rawScore/maximumScore*100:50)));
 const reasons=b.filter(i=>i.state==="MATCH").sort((a,c)=>c.weight-a.weight).map(i=>i.detail).filter(Boolean).slice(0,4),tradeOffs=b.filter(i=>i.state==="MISMATCH"||i.state==="PARTIAL").sort((a,c)=>c.weight-a.weight).map(i=>i.detail).filter(Boolean).slice(0,4),unknowns=b.filter(i=>i.state==="UNKNOWN").map(i=>i.detail).filter(Boolean);
 return{vehicle:v,score,rawScore:Number(rawScore.toFixed(2)),maximumScore:Number(maximumScore.toFixed(2)),strongMatches:b.filter(i=>i.state==="MATCH").length,withinBudget:budget===undefined||v.price<=budget,budgetDistance:budget===undefined?0:Math.abs(v.price-budget),breakdown:b,reasons:reasons.length?reasons:["One of the closest available options based on your answers"],tradeOffs,unknowns};
}
export function rankVehicles(vehicles:Vehicle[],p:CarPreference){const ranked=vehicles.map(v=>scoreCarForPreferences(v,p)).sort((a,b)=>b.score-a.score||b.strongMatches-a.strongMatches||Number(b.withinBudget)-Number(a.withinBudget)||a.budgetDistance-b.budgetDistance||b.vehicle.year-a.vehicle.year||a.vehicle.id.localeCompare(b.vehicle.id));return{ranked}}
