import {criteria} from "./criteria";
import type {CarPreference,PriorityKey,Vehicle} from "@/types";
export type Rejection={vehicleId:string;reasons:string[]};
export type ScoredVehicle={vehicle:Vehicle;score:number;breakdown:Record<string,number>;reasons:string[];tradeOffs:string[]};
const ratings:Record<PriorityKey,(v:Vehicle)=>number|undefined>={fuelEconomy:v=>v.fuelEconomyRating,reliability:v=>v.reliabilityRating,maintenance:v=>v.maintenanceCostRating,comfort:v=>v.comfortRating,performance:v=>v.performanceRating,practicality:v=>v.practicalityRating,appearance:v=>v.condition.body};
export function hardConstraintReasons(v:Vehicle,p:CarPreference){const r:string[]=[];if(p.budget?.max!==undefined&&v.price>p.budget.max)r.push("above maximum budget");if(p.budget?.min!==undefined&&v.price<p.budget.min)r.push("below minimum budget");if(p.transmission&&p.transmission!=="NO_PREFERENCE"&&v.transmission!==p.transmission)r.push("wrong transmission");if(p.engineHealth?.minimum!==undefined&&(v.condition.engine??-1)<p.engineHealth.minimum)r.push("engine health below minimum");if(p.mileage?.maximum!==undefined&&v.mileage>p.mileage.maximum)r.push("mileage above maximum");if(p.seatingCapacity?.minimum!==undefined&&(v.numberOfSeats??0)<p.seatingCapacity.minimum)r.push("not enough seats");if(p.year?.min!==undefined&&v.year<p.year.min)r.push("older than minimum year");if(p.year?.max!==undefined&&v.year>p.year.max)r.push("newer than maximum year");if(p.preferredBodyTypes?.length&&!p.preferredBodyTypes.includes(v.bodyType))r.push("different body type");if(p.excludedMakes?.includes(v.make))r.push("excluded make");return r}
export function normalizeWeights(priorities:CarPreference["priorities"]){const total=Object.values(priorities).reduce((a,b)=>a+Math.max(0,b),0);const out={} as Record<PriorityKey,number>;for(const k of Object.keys(priorities) as PriorityKey[])out[k]=total?Math.max(0,priorities[k])/total:1/7;return out}
export function rankVehicles(vehicles:Vehicle[],p:CarPreference){const rejected:Rejection[]=[];const weights=normalizeWeights(p.priorities);const ranked=vehicles.flatMap(vehicle=>{const reasons=hardConstraintReasons(vehicle,p);if(reasons.length){rejected.push({vehicleId:vehicle.id,reasons});return []}let sum=0,covered=0;const breakdown:Record<string,number>={};for(const key of Object.keys(weights) as PriorityKey[]){const rating=ratings[key](vehicle);if(rating!==undefined){const contribution=rating*weights[key];sum+=contribution;covered+=weights[key];breakdown[key]=Number(contribution.toFixed(1))}}let score=covered?sum/covered:0;if(p.preferredMakes?.includes(vehicle.make))score+=2;if(vehicle.inspectionStatus==="VERIFIED_INSPECTION")score+=2;score=Math.max(0,Math.min(100,score));const fit:string[]=[];const tradeOffs:string[]=[];
if(p.budget?.max!==undefined)fit.push("Within your maximum budget");
if(p.transmission&&p.transmission!=="NO_PREFERENCE")fit.push("Meets your transmission requirement");
if(p.seatingCapacity?.minimum)fit.push(`Seats at least ${p.seatingCapacity.minimum}`);
for(const {key,label} of [...criteria].sort((a,b)=>weights[b.key]-weights[a.key])){const rating=ratings[key](vehicle);if(rating===undefined){if(weights[key]>0)tradeOffs.push(`${label}: no rating supplied`)}else if(rating>=80&&weights[key]>0)fit.push(`${label}: ${rating}/100`);else if(rating<65&&weights[key]>0)tradeOffs.push(`${label}: ${rating}/100 - a weaker area`)}
if(!covered)tradeOffs.push("Insufficient rating data to assess your priorities");
if(vehicle.inspectionStatus!=="VERIFIED_INSPECTION")tradeOffs.push("Condition has not been independently verified");
return [{vehicle,score:Number(score.toFixed(1)),breakdown,reasons:fit.length?fit:["Meets your required filters; review the available ratings"],tradeOffs}]}).sort((a,b)=>b.score-a.score||a.vehicle.id.localeCompare(b.vehicle.id));return{ranked,rejected}}
export function analyzeNoMatch(vehicles:Vehicle[],p:CarPreference){const result=rankVehicles(vehicles,p);if(result.ranked.length)return[];const counts=new Map<string,number>();for(const x of result.rejected)for(const r of x.reasons)counts.set(r,(counts.get(r)||0)+1);return [...counts].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([constraint,count])=>({constraint,count}))}
