"use client";
import {useRef} from "react";
import {useScroll,useTransform,type MotionValue} from "motion/react";
import * as m from "motion/react-m";
import {useMotionPolicy} from "./use-motion-policy";
import {MotionCTA} from "./cta";
import {TextReveal} from "./reveal";
function StoryStep({progress,index,title,copy,depth}:{progress:MotionValue<number>;index:number;title:string;copy:string;depth:boolean}){const opacity=useTransform(progress,[index*.19,index*.19+.15],[.45,1]);const scaleX=useTransform(progress,[index*.19,index*.19+.15],[0,1]);return <m.div className="story-step" style={{opacity:depth?opacity:1}}><span className="technical">0{index+1}</span><div><h3>{title}</h3><p>{copy}</p><span className="story-step-track" aria-hidden><m.span style={{scaleX:depth?scaleX:1}}/></span></div></m.div>}
export function DecisionStory(){const target=useRef<HTMLDivElement>(null);const{depth}=useMotionPolicy();const{scrollYProgress}=useScroll({target,offset:["start .75","end .8"]});const resultOpacity=useTransform(scrollYProgress,[.65,.95],[.5,1]);return <section ref={target} className={`decision-intro decision-story section-space ${depth?"story-desktop":""}`}><div className="container story-composition"><div className="story-heading"><p className="eyebrow">Less searching. More direction.</p><TextReveal lines={["Tell us","what matters."]}/><p className="section-copy mt-6">Not sure which car is right for you? Decision Support turns your budget, must-haves and priorities into a shortlist with reasons behind it.</p><div className="mt-7"><MotionCTA href="/car-adviser" magnetic>Start my decision</MotionCTA></div><p className="mt-4 text-sm text-[#69756f]">Guided research. No account needed to see your matches.</p></div><div className="story-interface"><p className="technical mb-8">Your priorities → A considered shortlist</p>{[["Set your budget","Cars above your maximum are excluded first."],["Choose reliability","Give dependable options more influence in the ranking."],["Consider fuel economy","Weigh efficiency using the available listing ratings."],["Keep maintenance in mind","Prioritize more affordable maintenance."]].map(([title,copy],index)=><StoryStep key={title} {...{title,copy,index,depth}} progress={scrollYProgress}/>)}<m.div className="story-outcome" style={{opacity:depth?resultOpacity:1}}><span className="technical">Then / Your strongest matches</span><h3>See the fit.<br/>Know the trade-offs.</h3><p>Your real results explain strengths, weaker areas and missing information. Try the live ranking preview below.</p></m.div></div></div></section>}
