import {Reveal,TextReveal} from "@/components/motion/reveal";
import {Stagger} from "@/components/motion/stagger";
import {Accordion} from "@/components/motion/accordion";
import {AnimatedNumber} from "@/components/motion/animated-number";
import {HeroVisual} from "@/components/motion/hero-visual";
import {MotionCTA} from "@/components/motion/cta";
import Link from "next/link";
import type {Vehicle} from "@/types";
import {VehicleImage} from "@/components/cars/vehicle-image";
import {money} from "@/lib/utils";
export function ComparisonShowcase({vehicles}:{vehicles:Vehicle[]}){const pair=vehicles.slice(0,2);return <section className="container section-space"><div className="section-heading"><div><p className="eyebrow">Put your finalists side by side</p><TextReveal lines={["Two good cars.","One better fit."]}/></div><p className="max-w-sm section-copy">Price, condition and everyday priorities. Compare what matters before you make the call.</p></div><div className="comparison-signature grid gap-6 md:grid-cols-2"><span className="comparison-vs" aria-hidden>VS</span>{pair.map((v,index)=><Reveal key={v.id} family={index===0?"left":"right"} delay={index*.08}><article><div className="relative aspect-[16/9] overflow-hidden rounded-2xl"><VehicleImage vehicle={v} sizes="(max-width: 768px) 100vw, 50vw"/></div><div className="flex flex-wrap justify-between gap-3 py-6"><h3 className="text-2xl font-bold">{v.make} {v.model}</h3><span>{money(v.price)}</span></div><dl>{[["Reliability",v.reliabilityRating],["Maintenance affordability",v.maintenanceCostRating],["Comfort",v.comfortRating]].map(([label,value])=><div key={label} className="flex justify-between border-t border-black/15 py-3 text-sm"><dt>{label}</dt><dd>{value===undefined?"Not rated":`${value}/100`}</dd></div>)}</dl></article></Reveal>)}</div><Link href={`/compare${pair.length?`?cars=${pair.map(v=>v.id).join(",")}`:""}`} className="btn btn-dark mt-8">Compare cars ↗</Link></section>}
export function InventorySection({count,makes}:{count:number;makes:string[]}){return <><section className="inventory-band"><div className="container grid gap-8 md:grid-cols-3">{[[count,"Active vehicle listings"],[makes.length,"Manufacturers in the catalogue"],[7,"Weighted evaluation criteria"]].map(([n,label])=><div key={label}><AnimatedNumber value={Number(n)}/><span>{label}</span></div>)}</div></section><section id="brands" className="container section-space"><div className="section-heading"><div><p className="eyebrow">Follow your curiosity</p><TextReveal lines={["A familiar badge.","A fresh perspective."]}/></div><p className="max-w-sm section-copy">Explore manufacturers with active listings. Let the individual car earn its place on your shortlist.</p></div><Stagger className="brand-list">{makes.map(make=><Link key={make} href={`/cars?make=${encodeURIComponent(make)}`}>{make}<span>↗</span></Link>)}</Stagger>{!makes.length&&<p>Manufacturers appear here as listings become available.</p>}</section></>}
const faqs=[["What is CarXSailor?","A place to research available cars in Nigeria, compare options and get guidance based on your priorities. Listings connect you with sellers."],["What does Decision Support mean?","A guided way to narrow your choices. You set requirements and priorities; we filter available cars, rank their ratings and explain the trade-offs."],["How are cars recommended?","Required limits are checked first. Seven weighted ratings produce a fit score, with small bonuses for preferred makes and verified inspections. Missing ratings are flagged, not invented."],["Do I need an account?","You can browse, complete Decision Support and compare cars without one. Sign in to save cars, keep decisions or contact a vendor."],["Can I compare two cars?","Yes. Choose Add to compare on a listing or select up to three vehicles on the Compare page."],["Does CarXSailor sell the cars?","Vehicles are listed by sellers. Use the listing’s contact options to discuss availability, viewing and purchase with the seller."],["Where does vehicle information come from?","From listing information and recorded condition reports. Each listing distinguishes vendor-reported condition from a verified inspection. Ratings are not ownership guarantees."],["Can I save my recommendations?","Yes. Choose Save my decision after seeing results. If you sign in first, your current answers and results are kept in this browser tab so you can return and save."]];
export function FAQ(){return <section className="faq-section section-space"><div className="container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Before you get going</p><TextReveal lines={["Good questions.","Clear answers."]}/><p className="mt-6 text-[#69756f]">Still need a hand? <Link className="underline" href="/contact">Talk to us.</Link></p></div><Accordion items={faqs}/></div></section>}
export function FinalCTA({vehicle}:{vehicle?:Vehicle}){return <section className="container py-16"><HeroVisual closing image={vehicle?<VehicleImage vehicle={vehicle}/>:null}><div className="relative z-10 max-w-2xl"><p className="eyebrow">The next move is yours</p><TextReveal lines={["Your next car deserves","a better decision."]}/><p className="mt-5 text-white/75">Start with your life. Find the car that belongs in it.</p><div className="mt-8 flex flex-wrap gap-3"><MotionCTA href="/car-adviser" className="btn-primary" magnetic>Find my car</MotionCTA><Link href="/cars" className="btn border-white/40 text-white">Browse cars</Link></div></div></HeroVisual></section>}
