"use client";
import {LayoutGroup} from "motion/react";
import * as m from "motion/react-m";
import {settle} from "@/lib/motion";
import {useMotionPolicy} from "@/components/motion/use-motion-policy";
import {TextReveal,Reveal} from "@/components/motion/reveal";
import {useState} from "react";
import Link from "next/link";
import type {Vehicle} from "@/types";
import {rankVehicles} from "@/lib/dss/engine";
import {criteria,defaultPreference} from "@/lib/dss/criteria";
export function DecisionPreview({vehicles}:{vehicles:Vehicle[]}){const{reduced}=useMotionPolicy();const[priorities,setPriorities]=useState(defaultPreference.priorities);const ranked=rankVehicles(vehicles,{...defaultPreference,priorities}).ranked.slice(0,3);return <section className="container section-space pt-0"><Reveal family="panel"><div className="preview-panel"><div><p className="eyebrow">Try the thinking behind the shortlist</p><TextReveal lines={["Your priorities","change the picture."]}/><p className="mt-5 max-w-md leading-7 text-white/65">Adjust a priority and watch these available listings reorder. This is a live example using the same scoring engine as Decision Support, without your budget filters.</p><div className="mt-8 grid gap-5">{criteria.slice(0,5).map(c=><label key={c.key}><span className="mb-2 flex justify-between gap-3 text-sm"><span>{c.label}</span><span className="text-[#d7f25c]">{priorities[c.key]===1?"Very important":priorities[c.key]>=.5?"Important":priorities[c.key]>0?"Moderate":"Not a priority"}</span></span><input className="w-full accent-[#d7f25c]" type="range" min="0" max="1" step=".25" value={priorities[c.key]} onChange={e=>setPriorities({...priorities,[c.key]:Number(e.target.value)})}/></label>)}</div></div><div className="preview-results"><p className="technical">Live example / {vehicles.length} listings</p><LayoutGroup><div aria-live="polite">{ranked.map((r,i)=><m.div layout={reduced?false:"position"} transition={settle} key={r.vehicle.id}><Link href={`/cars/${r.vehicle.slug}`} className="preview-match"><span className="technical">0{i+1}</span><div><h3>{r.vehicle.make} {r.vehicle.model}</h3><p>{r.reasons[0]}</p></div><strong>{r.score}<small>/100</small></strong></Link></m.div>)}</div></LayoutGroup>{!ranked.length&&<p className="py-8">The preview will appear when listings are available.</p>}<p className="mt-6 text-sm leading-6 text-white/55">Fit scores rank available ratings, with small bonuses for verified inspections and preferred makes. They are not guarantees. Missing ratings are excluded and flagged in your results.</p><Link href="/car-adviser" className="btn btn-primary mt-8">Build my own shortlist ↗</Link></div></div></Reveal></section>}
