import {TextReveal} from "@/components/motion/reveal";
import {Stagger} from "@/components/motion/stagger";
import {DecisionStory} from "@/components/motion/decision-story";
import {ProcessTimeline} from "@/components/motion/process-timeline";
import {WordHighlight} from "@/components/motion/word-highlight";
import Link from "next/link";

import {criteria} from "@/lib/dss/criteria";
export function DecisionIntro(){return <DecisionStory/>}
export function DecisionCriteria(){return <section className="dark-section section-space"><div className="container grid gap-16 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Look beyond the badge</p><WordHighlight text="Buying a car shouldn’t feel like guesswork."/><p className="mt-7 max-w-sm leading-8 text-white/65">Looks and reputation can start the conversation. Your budget, day-to-day needs and the condition of the actual car should help finish it.</p><div className="mt-12 border-l-2 border-[#d7f25c] pl-5 text-lg">First, your requirements.<br/><span className="text-white/55">Then, the trade-offs.</span></div></div><Stagger>{criteria.map((c,i)=><div key={c.key} className="criteria-row"><span className="technical">0{i+1}</span><div><h3>{c.label}</h3><p>{c.description}</p></div><span className="text-[#d7f25c]">↗</span></div>)}</Stagger></div></section>}
export function DecisionProcess(){return <section id="how-it-works" className="container section-space"><div className="section-heading"><div><p className="eyebrow">From undecided to a shortlist</p><TextReveal lines={["A few questions.","A clearer next step."]}/></div><Link className="btn btn-dark" href="/car-adviser">Start my decision ↗</Link></div><ProcessTimeline/></section>}
export function Benefits(){return <section className="benefits-section section-space"><div className="container"><p className="eyebrow">Why CarXSailor</p><TextReveal lines={["The specs are only","half the story."]}/><Stagger className="mt-14 grid gap-10 md:grid-cols-3">{[["Context before commitment","A car can be excellent and still be wrong for your budget. Start with what works for you."],["Trade-offs in plain sight","See what a vehicle does well, where its ratings are weaker and which information is missing."],["One place to think it through","Move from discovery to decisions, comparisons and saved cars without rebuilding your shortlist."]].map(([title,copy],i)=><div key={title} className="border-t border-black/20 pt-6"><span className="technical">0{i+1} /</span><h3 className="my-4 text-xl font-bold">{title}</h3><p className="leading-7 text-[#58645d]">{copy}</p></div>)}</Stagger></div></section>}
