import type {Vehicle} from "@/types";
const image=(id:string)=>[{url:`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=82`,alt:"Vehicle exterior",isPrimary:true,order:0}];
export const demoVehicles:Vehicle[]=[
{id:"1",vendorId:"v1",slug:"2010-toyota-corolla-lagos",title:"2010 Toyota Corolla",description:"A clean, dependable automatic sedan with excellent engine health and a tidy interior.",make:"Toyota",model:"Corolla",year:2010,price:4750000,mileage:118000,transmission:"AUTOMATIC",fuelType:"PETROL",bodyType:"SEDAN",location:{country:"Nigeria",state:"Lagos",city:"Ikeja"},images:image("1550355291-bbee04a92027"),features:["Air conditioning","Reverse camera","Bluetooth"],condition:{overall:91,engine:94,transmission:90,suspension:86,body:88,interior:91},fuelEconomyRating:90,reliabilityRating:95,maintenanceCostRating:93,comfortRating:76,performanceRating:68,practicalityRating:81,inspectionStatus:"VERIFIED_INSPECTION",numberOfSeats:5,origin:"FOREIGN_USED",status:"ACTIVE",isFeatured:true,createdAt:"2026-08-10"},
{id:"2",vendorId:"v2",slug:"2010-honda-civic-abuja",title:"2010 Honda Civic",description:"Sporty, efficient compact sedan with responsive handling and a healthy drivetrain.",make:"Honda",model:"Civic",year:2010,price:4400000,mileage:126500,transmission:"AUTOMATIC",fuelType:"PETROL",bodyType:"SEDAN",location:{country:"Nigeria",state:"FCT",city:"Abuja"},images:image("1549317661-bd32c8ce0db2"),features:["Alloy wheels","Cruise control","Air conditioning"],condition:{overall:87,engine:91,transmission:88,suspension:83,body:84,interior:87},fuelEconomyRating:88,reliabilityRating:89,maintenanceCostRating:84,comfortRating:74,performanceRating:76,practicalityRating:78,inspectionStatus:"VERIFIED_INSPECTION",numberOfSeats:5,origin:"FOREIGN_USED",status:"ACTIVE",isFeatured:false,createdAt:"2026-08-08"},
{id:"3",vendorId:"v1",slug:"2009-toyota-camry-benin",title:"2009 Toyota Camry",description:"Comfortable and roomy sedan, ideal for work and longer intercity journeys.",make:"Toyota",model:"Camry",year:2009,price:4950000,mileage:139000,transmission:"AUTOMATIC",fuelType:"PETROL",bodyType:"SEDAN",location:{country:"Nigeria",state:"Edo",city:"Benin City"},images:image("1492144534655-ae79c964c9d7"),features:["Leather seats","Cruise control","Dual-zone AC"],condition:{overall:85,engine:90,transmission:86,suspension:82,body:83,interior:86},fuelEconomyRating:72,reliabilityRating:91,maintenanceCostRating:85,comfortRating:89,performanceRating:73,practicalityRating:85,inspectionStatus:"VENDOR_REPORTED",numberOfSeats:5,origin:"NIGERIAN_USED",status:"ACTIVE",isFeatured:true,createdAt:"2026-08-05"},
{id:"4",vendorId:"v3",slug:"2014-hyundai-elantra-lagos",title:"2014 Hyundai Elantra",description:"Modern, fuel-conscious sedan with a refined cabin and useful everyday features.",make:"Hyundai",model:"Elantra",year:2014,price:6800000,mileage:98000,transmission:"AUTOMATIC",fuelType:"PETROL",bodyType:"SEDAN",location:{country:"Nigeria",state:"Lagos",city:"Lekki"},images:image("1503376780353-7e6692767b70"),features:["Keyless entry","Bluetooth","USB audio"],condition:{overall:89,engine:92,transmission:89,suspension:87,body:88,interior:91},fuelEconomyRating:86,reliabilityRating:82,maintenanceCostRating:82,comfortRating:84,performanceRating:72,practicalityRating:80,inspectionStatus:"VERIFIED_INSPECTION",numberOfSeats:5,origin:"FOREIGN_USED",status:"ACTIVE",isFeatured:false,createdAt:"2026-08-13"},
{id:"5",vendorId:"v2",slug:"2012-toyota-rav4-port-harcourt",title:"2012 Toyota RAV4",description:"Practical compact SUV with strong reliability and versatile luggage space.",make:"Toyota",model:"RAV4",year:2012,price:8900000,mileage:112000,transmission:"AUTOMATIC",fuelType:"PETROL",bodyType:"SUV",location:{country:"Nigeria",state:"Rivers",city:"Port Harcourt"},images:image("1449965408869-eaa3f722e40d"),features:["4WD","Roof rails","Reverse camera"],condition:{overall:90,engine:93,transmission:90,suspension:88,body:87,interior:89},fuelEconomyRating:74,reliabilityRating:94,maintenanceCostRating:86,comfortRating:85,performanceRating:78,practicalityRating:93,inspectionStatus:"VERIFIED_INSPECTION",numberOfSeats:5,origin:"FOREIGN_USED",status:"ACTIVE",isFeatured:true,createdAt:"2026-08-16"},
{id:"6",vendorId:"v4",slug:"2011-lexus-rx350-asaba",title:"2011 Lexus RX 350",description:"Premium comfort, polished road manners and a well-kept leather cabin.",make:"Lexus",model:"RX 350",year:2011,price:11900000,mileage:121000,transmission:"AUTOMATIC",fuelType:"PETROL",bodyType:"SUV",location:{country:"Nigeria",state:"Delta",city:"Asaba"},images:image("1503736334956-4c8f8e92946d"),features:["Leather seats","Sunroof","Navigation","Power tailgate"],condition:{overall:88,engine:91,transmission:89,suspension:85,body:87,interior:92},fuelEconomyRating:60,reliabilityRating:88,maintenanceCostRating:62,comfortRating:95,performanceRating:85,practicalityRating:89,inspectionStatus:"VENDOR_REPORTED",numberOfSeats:5,origin:"FOREIGN_USED",status:"ACTIVE",isFeatured:true,createdAt:"2026-08-11"}];
export const getVehicle=(slug:string)=>demoVehicles.find(v=>v.slug===slug);
