"use client";
import {AnimatePresence} from "motion/react";
import * as m from "motion/react-m";
import {directional,settle} from "@/lib/motion";
import {useMotionPolicy} from "@/components/motion/use-motion-policy";
import {useSyncExternalStore,useRef,useState} from "react";
import {criteria,defaultPreference,preferenceSchema} from "@/lib/dss/preferences";
import {formatNaira,parseNairaBudget} from "@/lib/dss/money";
import type {CarPreference,DecisionUseCase,PriorityKey} from "@/types";
import type {AdviserResponse} from "@/lib/ai/types";
import {Results} from "./results";

const steps=["Budget","Main use","Vehicle type","Top priorities","Other preferences"];
const uses:{value:DecisionUseCase;label:string;copy:string}[]=[
 {value:"DAILY",label:"Daily driving",copy:"Commuting, errands and everyday running costs"},
 {value:"FAMILY",label:"Family",copy:"Space and comfort for everyday family use"},
 {value:"BUSINESS",label:"Business / work",copy:"Dependability and sensible running costs"},
 {value:"LONG_DISTANCE",label:"Long trips",copy:"Comfort and efficiency over longer journeys"},
 {value:"ROUGH_ROADS",label:"Rough roads",copy:"Body type and recorded suspension condition"},
 {value:"PERFORMANCE",label:"Fun / performance",copy:"Prioritise the stored performance rating"},
 {value:"LUXURY",label:"Luxury / comfort",copy:"Cabin, body condition and comfort ratings"},
];
const bodies=["SUV","SEDAN","HATCHBACK","PICKUP","MINIVAN","COUPE"] as const;
const subscribe=()=>()=>{};
function restored(resume:boolean){try{const draft=JSON.parse(sessionStorage.getItem("carxsailor-draft")||"null"),parsed=preferenceSchema.safeParse(draft?.preference);const preference=parsed.success?{...defaultPreference,...parsed.data}:defaultPreference;let data:AdviserResponse|null=null;if(resume){const result=JSON.parse(sessionStorage.getItem("carxsailor-results")||"null");if(preferenceSchema.safeParse(result?.preference).success)data=result}return{preference:data?.preference??preference,step:data?4:parsed.success&&Number.isInteger(draft?.step)?Math.max(-1,Math.min(4,draft.step)):-1,data,budgetText:preference.budget?.max?String(preference.budget.max/1_000_000):""}}catch{return{preference:defaultPreference,step:-1,data:null,budgetText:""}}}
export function GuidedAdviser({resume=false}:{resume?:boolean}){const ready=useSyncExternalStore(subscribe,()=>true,()=>false);return <GuidedForm key={String(ready)+"-"+resume} restore={ready} resume={resume}/>}
function Choice({selected,onClick,children,copy}:{selected:boolean;onClick:()=>void;children:React.ReactNode;copy?:string}){return <button type="button" className="decision-choice" aria-pressed={selected} onClick={onClick}><strong>{children}</strong>{copy&&<span>{copy}</span>}</button>}
function GuidedForm({restore,resume}:{restore:boolean;resume:boolean}){
 const{reduced}=useMotionPolicy(),[direction,setDirection]=useState(1),[initial]=useState(()=>restore?restored(resume):{preference:defaultPreference,step:-1,data:null,budgetText:""}),[step,setStep]=useState(initial.step),[p,setP]=useState<CarPreference>(initial.preference),[budgetText,setBudgetText]=useState(initial.budgetText),[data,setData]=useState<AdviserResponse|null>(initial.data),[busy,setBusy]=useState(false),[error,setError]=useState(""),heading=useRef<HTMLElement>(null);
 function change(next:CarPreference){setP(next);setError("");try{sessionStorage.setItem("carxsailor-draft",JSON.stringify({preference:next,step}))}catch{}}
 function move(next:number){setDirection(next>step?1:-1);setStep(next);setData(null);setError("");try{sessionStorage.setItem("carxsailor-draft",JSON.stringify({preference:p,step:next}))}catch{}setTimeout(()=>heading.current?.focus(),0)}
 function setBudget(raw:string){setBudgetText(raw);const amount=parseNairaBudget(raw);change({...p,budget:amount?{max:amount}:undefined})}
 function togglePriority(key:PriorityKey){const selected=p.priorities[key]>0,count=Object.values(p.priorities).filter(value=>value>0).length;if(!selected&&count>=3){setError("Choose up to three priorities.");return}change({...p,priorities:{...p.priorities,[key]:selected?0:1}})}
 async function generate(){if(busy)return;setBusy(true);setError("");const summary=[p.budget?.max&&formatNaira(p.budget.max)+" budget",p.useCase&&uses.find(item=>item.value===p.useCase)?.label,p.preferredBodyTypes?.[0],...criteria.filter(item=>p.priorities[item.key]>0).map(item=>item.label)].filter(Boolean).join(" / ");const preference={...p,interpretedSummary:summary||"Flexible preferences"};try{const response=await fetch("/api/adviser/recommend",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({preference})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Please try again.");setP(preference);setData(result);try{sessionStorage.setItem("carxsailor-results",JSON.stringify(result));sessionStorage.setItem("carxsailor-draft",JSON.stringify({preference,step}))}catch{}setTimeout(()=>document.getElementById("results")?.scrollIntoView({behavior:reduced?"auto":"smooth"}),100)}catch(e){setError(e instanceof Error?e.message:"Could not load recommendations.")}finally{setBusy(false)}}
 function submit(e:React.FormEvent){e.preventDefault();if(step===0&&!p.budget?.max){setError("Enter a budget such as 10 or choose a quick amount.");return}if(step<4)move(step+1);else void generate()}
 const selectedCount=Object.values(p.priorities).filter(value=>value>0).length;
 return <div id="guided">{!data&&<div className="question-panel">{step===-1?<><p className="eyebrow">Decision Support / Start here</p><h2 ref={node=>{heading.current=node}} tabIndex={-1} className="mt-4">Let&apos;s find the right car for you.</h2><p className="mt-5 text-lg leading-8 text-[#69756f]">You don&apos;t need to know cars. Tell us what matters and we&apos;ll rank every available car by how well it fits.</p><p className="mt-5 text-sm font-bold">5 short questions - No sign-in required</p><button className="btn btn-dark mt-8" onClick={()=>move(0)}>Start finding my car</button></>:<><div className="flex justify-between gap-3 text-sm"><span>Step {step+1} of {steps.length}</span><span>{steps[step]}</span></div><div className="decision-progress-track" role="progressbar" aria-label="Questionnaire progress" aria-valuenow={step+1} aria-valuemin={1} aria-valuemax={steps.length}><m.span initial={false} animate={{scaleX:(step+1)/steps.length}} transition={reduced?{duration:0}:settle}/></div><form onSubmit={submit}><div className="question-motion-viewport"><AnimatePresence initial={false} mode="wait" custom={direction}><m.div className="my-7 grid gap-6" key={step} custom={direction} variants={directional(reduced)} initial="enter" animate="center" exit="exit">
 {step===0&&<><h2 ref={node=>{heading.current=node}} tabIndex={-1}>What&apos;s the most you&apos;d like to spend?</h2><div className="budget-field"><span aria-hidden>{"\u20A6"}</span><label><span className="sr-only">Maximum budget in millions of naira</span><input value={budgetText} onChange={e=>setBudget(e.target.value)} inputMode="decimal" placeholder="10" autoFocus/></label><b>million</b></div><p className="budget-helper" aria-live="polite">{p.budget?.max?formatNaira(p.budget.max)+" maximum budget":"Enter 7.5 for \u20A67,500,000"}</p><div className="decision-chips" aria-label="Quick budget choices">{[5,10,15,20,30].map(value=><button type="button" aria-pressed={p.budget?.max===value*1_000_000} key={value} onClick={()=>setBudget(String(value))}>{"\u20A6"}{value}m{value===30?"+":""}</button>)}</div><p className="text-sm text-[#69756f]">Cars above your budget stay in the ranking, with the difference shown clearly.</p></>}
 {step===1&&<fieldset><legend ref={node=>{heading.current=node}} tabIndex={-1} className="text-2xl font-bold">What will you mostly use the car for?</legend><div className="decision-choice-grid mt-6">{uses.map(item=><Choice key={item.value} selected={p.useCase===item.value} onClick={()=>change({...p,useCase:p.useCase===item.value?undefined:item.value})} copy={item.copy}>{item.label}</Choice>)}</div><button type="button" className="text-link mt-6" onClick={()=>{change({...p,useCase:undefined});move(2)}}>I&apos;m not sure - skip</button></fieldset>}
 {step===2&&<fieldset><legend ref={node=>{heading.current=node}} tabIndex={-1} className="text-2xl font-bold">What kind of car are you considering?</legend><div className="decision-choice-grid mt-6">{bodies.map(body=><Choice key={body} selected={p.preferredBodyTypes?.[0]===body} onClick={()=>change({...p,preferredBodyTypes:p.preferredBodyTypes?.[0]===body?[]:[body]})}>{body.charAt(0)+body.slice(1).toLowerCase()}</Choice>)}<Choice selected={!p.preferredBodyTypes?.length} onClick={()=>change({...p,preferredBodyTypes:[]})}>Any / surprise me</Choice></div></fieldset>}
 {step===3&&<fieldset><legend ref={node=>{heading.current=node}} tabIndex={-1} className="text-2xl font-bold">What matters most to you?</legend><p className="mt-2 text-sm text-[#69756f]">Choose up to 3. These use ratings stored on each listing.</p><div className="decision-choice-grid mt-6">{criteria.map(item=><Choice key={item.key} selected={p.priorities[item.key]>0} onClick={()=>togglePriority(item.key)} copy={item.description}>{item.label}</Choice>)}</div><p className="text-sm font-bold">{selectedCount} of 3 selected</p></fieldset>}
 {step===4&&<><h2 ref={node=>{heading.current=node}} tabIndex={-1}>Any other preferences?</h2><p className="text-sm text-[#69756f]">Everything here is optional. Choose &quot;Any&quot; when you&apos;re flexible.</p><div className="grid gap-5 sm:grid-cols-2"><label><span className="label">Transmission</span><select className="input" value={p.transmission??"NO_PREFERENCE"} onChange={e=>change({...p,transmission:e.target.value as CarPreference["transmission"]})}><option value="NO_PREFERENCE">Any transmission</option><option value="AUTOMATIC">Automatic</option><option value="MANUAL">Manual</option><option value="CVT">CVT</option></select></label><label><span className="label">Fuel type</span><select className="input" value={p.fuelType??"NO_PREFERENCE"} onChange={e=>change({...p,fuelType:e.target.value as CarPreference["fuelType"]})}><option value="NO_PREFERENCE">Any fuel type</option>{["PETROL","DIESEL","HYBRID","ELECTRIC"].map(value=><option key={value}>{value}</option>)}</select></label><label><span className="label">Minimum seats</span><select className="input" value={p.seatingCapacity?.minimum??0} onChange={e=>change({...p,seatingCapacity:Number(e.target.value)?{minimum:Number(e.target.value)}:undefined})}><option value="0">Any seat count</option>{[4,5,6,7,8].map(value=><option value={value} key={value}>{value} seats</option>)}</select></label><label><span className="label">Preferred minimum year</span><select className="input" value={p.year?.min??0} onChange={e=>change({...p,year:Number(e.target.value)?{min:Number(e.target.value)}:undefined})}><option value="0">Any year</option>{[2022,2020,2018,2015,2010].map(value=><option key={value}>{value} or newer</option>)}</select></label><label><span className="label">Vehicle condition</span><select className="input" value={p.origin??"NO_PREFERENCE"} onChange={e=>change({...p,origin:e.target.value as CarPreference["origin"]})}><option value="NO_PREFERENCE">Any condition</option><option value="BRAND_NEW">Brand new</option><option value="FOREIGN_USED">Foreign used</option><option value="NIGERIAN_USED">Nigerian used</option></select></label></div></>}
 </m.div></AnimatePresence></div>{error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}<div className="decision-actions"><button type="button" className="btn btn-light" disabled={busy} onClick={()=>move(step-1)}>Back</button><button className="btn btn-dark" disabled={busy}>{busy?"Ranking cars for your needs...":step===4?"Find my matches":"Continue"}</button></div></form></>}</div>}{data&&<Results data={data} onEdit={()=>move(0)}/>}</div>
}
