import {writeFile} from "node:fs/promises";
const target=await(await fetch("http://127.0.0.1:9222/json/new?about:blank",{method:"PUT"})).json();
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener("open",r,{once:true}));let id=0;const calls=new Map();const errors=[];
ws.addEventListener("message",e=>{const m=JSON.parse(e.data);if(m.method==="Runtime.exceptionThrown")errors.push(m.params.exceptionDetails.text);if(m.id){const call=calls.get(m.id);calls.delete(m.id);if(m.error)call.reject(m.error);else call.resolve(m.result)}});
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;calls.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
async function evaluate(expression){const r=await send("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value}
const pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(expression){for(let i=0;i<120;i++){if(await evaluate(expression))return;await pause(400)}throw new Error("Timed out: "+expression)}
const base=process.env.REVIEW_URL||"http://localhost:3000";
async function nav(path="/"){await send("Page.navigate",{url:base+path});await until('document.readyState==="complete" && !!document.querySelector("h1")');await pause(1400)}
function assert(ok,label){if(!ok)throw new Error(label);console.log("PASS "+label)}
async function screenshot(name){const img=await send("Page.captureScreenshot",{format:"png"});await writeFile(`artifacts/${name}.png`,Buffer.from(img.data,"base64"))}
await send("Page.enable");await send("Page.bringToFront");await send("Runtime.enable");await send("Emulation.setDeviceMetricsOverride",{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await nav();await screenshot("motion-hero-desktop");assert(await evaluate('document.querySelector("h1").getAttribute("aria-label")==="Find the car. That fits your life."'),"Masked heading has a complete accessible name");
await evaluate('document.querySelector(".featured-layout").scrollIntoView({behavior:"instant",block:"center"})');await pause(1000);await evaluate('document.querySelectorAll(".vehicle-selector button")[1].click()');await pause(850);assert(await evaluate('document.querySelectorAll(".vehicle-selector button")[1].getAttribute("aria-pressed")==="true"'),"Featured forward selection settles");await evaluate('document.querySelectorAll(".vehicle-selector button")[0].click()');await pause(850);await screenshot("motion-featured-desktop");assert(await evaluate('document.querySelectorAll(".vehicle-selector button")[0].getAttribute("aria-pressed")==="true"'),"Featured reverse selection settles");
await evaluate('document.querySelector(".preview-panel").scrollIntoView({behavior:"instant",block:"center"})');await pause(1000);await screenshot("motion-preview-desktop");
await evaluate('document.querySelector(".faq-section").scrollIntoView({behavior:"instant",block:"center"})');await pause(800);await evaluate('document.querySelector(".faq-trigger").focus()');await send("Input.dispatchKeyEvent",{type:"keyDown",key:"Enter",code:"Enter",text:"\r",windowsVirtualKeyCode:13});await send("Input.dispatchKeyEvent",{type:"keyUp",key:"Enter",code:"Enter",windowsVirtualKeyCode:13});await pause(650);assert(await evaluate('document.querySelector(".faq-trigger").getAttribute("aria-expanded")==="true"'),"FAQ opens with the keyboard");await screenshot("motion-faq-desktop");
await send("Emulation.setDeviceMetricsOverride",{width:820,height:1000,deviceScaleFactor:1,mobile:true});await nav();assert(await evaluate('document.documentElement.scrollWidth<=innerWidth && getComputedStyle(document.querySelector(".mobile-toggle")).display!=="none"'),"Tablet navigation remains available without overflow");
await send("Emulation.setEmulatedMedia",{features:[{name:"prefers-reduced-motion",value:"reduce"}]});await send("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:true});await nav();assert(await evaluate('getComputedStyle(document.querySelector(".hero-image-layer")).transform==="none"'),"Reduced motion removes hero transforms");assert(await evaluate('!document.querySelector(".story-desktop")'),"Reduced motion removes sticky storytelling");await screenshot("motion-reduced-mobile");
await send("Emulation.setEmulatedMedia",{features:[{name:"prefers-reduced-motion",value:"no-preference"}]});await send("Emulation.setCPUThrottlingRate",{rate:4});await nav();
await evaluate('window.__reviewCLS=0;new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput)window.__reviewCLS+=e.value}).observe({type:"layout-shift",buffered:true})');
const sampling=await evaluate(`new Promise(resolve=>{let last=performance.now();const frames=[];function frame(now){frames.push(now-last);last=now;if(frames.length<90)requestAnimationFrame(frame);else resolve({frames:frames.length,over50ms:frames.filter(x=>x>50).length,maxMs:Math.round(Math.max(...frames))})}requestAnimationFrame(frame);window.scrollTo({top:1600,behavior:"smooth"})})`);
assert(await evaluate('document.documentElement.scrollWidth<=innerWidth'),"Throttled mobile page has no horizontal overflow");
const cls=await evaluate('window.__reviewCLS');const images=await evaluate('[...document.querySelectorAll("img")].filter(x=>x.complete&&x.naturalWidth===0).length');const resources=await evaluate('performance.getEntriesByType("resource").filter(x=>x.initiatorType==="script").reduce((sum,x)=>sum+x.encodedBodySize,0)');
await send("Emulation.setCPUThrottlingRate",{rate:1});await send("Emulation.setScriptExecutionDisabled",{value:true});await send("Page.navigate",{url:base+"/"});await pause(5000);const noJS=await evaluate('!!document.querySelector("h1") && document.querySelector("h1").getBoundingClientRect().height>0 && [...document.querySelectorAll("main a")].some(x=>x.getAttribute("href")==="/car-adviser")');assert(noJS,"Homepage copy and primary links remain server-rendered without JavaScript");await screenshot("motion-no-js-mobile");
await writeFile("artifacts/motion-performance.json",JSON.stringify({environment:base,cpuThrottle:4,viewport:"390x844",observedCLS:cls,frameSample:sampling,completedBrokenImages:images,scriptEncodedBytes:resources,runtimeExceptions:errors,noJS},null,2));
assert(errors.length===0,"No uncaught browser exceptions during motion review");console.log(JSON.stringify({observedCLS:cls,frameSample:sampling,scriptEncodedBytes:resources}));await send("Emulation.setScriptExecutionDisabled",{value:false});ws.close();await fetch(`http://127.0.0.1:9222/json/close/${target.id}`);
