"use client";
import {useRouter} from "next/navigation";

import * as m from "motion/react-m";
import {useMotionPolicy} from "@/components/motion/use-motion-policy";
import {timing} from "@/lib/motion";
import {Heart} from "lucide-react";
import {useEffect,useState} from "react";
import {useSession} from "@/lib/auth-client";
export function FavoriteButton({vehicleId}:{vehicleId:string}){const{reduced}=useMotionPolicy();const router=useRouter();const{data:session,isPending}=useSession();const[saved,setSaved]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");useEffect(()=>{let active=true;if(!session)return;fetch("/api/favorites?vehicleId="+encodeURIComponent(vehicleId)).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active)setSaved(data.saved)}).catch(()=>{if(active)setError("Could not check saved status.")});return()=>{active=false}},[vehicleId,session]);async function toggle(){if(!session){try{sessionStorage.setItem("carxsailor-pending-save",vehicleId)}catch{}router.push("/login?next="+encodeURIComponent(window.location.pathname+window.location.search));return}setBusy(true);setError("");try{const r=await fetch("/api/favorites",{method:saved?"DELETE":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({vehicleId})});if(r.status===401){router.push("/login?next="+encodeURIComponent(window.location.pathname+window.location.search));return}if(!r.ok)throw new Error("Could not save. Try again.");setSaved(!saved)}catch(e){setError(e instanceof Error?e.message:"Try again.")}finally{setBusy(false)}}return <div><m.button whileTap={reduced?undefined:{scale:.97}} disabled={busy||isPending} onClick={toggle} aria-label={session&&saved?"Remove saved car":"Save car"} title={session&&saved?"Remove saved car":"Save car"} aria-pressed={!!session&&saved} className="grid h-11 w-11 place-items-center rounded-full border border-[#dce2dd] bg-white text-[#163f31] disabled:opacity-50"><m.span key={saved?"saved":"unsaved"} animate={saved&&!reduced?{scale:[1,1.12,1]}:{scale:1}} transition={{duration:timing.micro}}><Heart size={18} fill={session&&saved?"currentColor":"none"}/></m.span></m.button>{error&&<span role="status" className="block max-w-40 rounded bg-white p-2 text-xs text-red-800">{error}</span>}</div>}
